### PR TITLE
Bundle Omise-PHP to the project

### PR DESCRIPTION
**Pull request by nimid**
#### 1. Objective

Bundle a library, Omise-PHP, to the project. Omise-PHP will be used to interface with Omise API.

**Related information**:
Related issue: -
Related ticket: -
Required pull request: #12 

#### 2. Description of change

- Add Omise-PHP to the project in the directory, `libraries\omise-php`
- A directory and files of Omise-PHP in the list below are not added to the project.
  1 `tests\`
  2 `.gitignore`
  3 `circle.yml`
  4 `composer.json`
  5 `phpunit.xml`

#### 3. Quality assurance

**Environments:**

- **Platform**: PrestaShop 1.6.1.6
- **Omise plugin**: Omise-PrestaShop 1.6.0.0
- **PHP**: 5.6.28
- **Omise-PHP**: 2.6.0

**Details:**

This pull request does not required testing.

#### 4. Impact of the change

`-`

#### 5. Priority of change

Normal

#### 6. Additional Notes

`-`

### CODE REVIEW

**Comment by guzzilar** [comment]
@nimid can you upgrade omise-php library to the latest one? ([2.6.0](https://github.com/omise/omise-php/releases/tag/v2.6.0))

Thanks & ok for the rest 👍

**Comment by guzzilar** [comment]
@nimid  fyi, going to rebase #12

**Comment by guzzilar** [comment]
rebased #12 `feature/create-card-token` => `feature/bundle-omise-php`

**Comment by guzzilar** [comment]
fyi, rebased with #12

**Comment by guzzilar** [comment]
fyi, rebased with `develop`

**Comment by nimid** [comment]
@guzzilar https://github.com/omise/omise-prestashop/pull/13#issuecomment-271860607

Done. 99b05488adae98849db7e919ad6da50de32d78a3

**Comment by guzzilar** [comment]
👍

**Pull request merged**
